<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    public function toArray()
    {
        return ['id' => $this->id, 'name' => $this->name]; // TODO: Change the autogenerated stub
    }
}
